/// Hive Types
const int HIVE_TYPE_ID_SIZE_WITH_INGREDIENT_VO = 1;
const int HIVE_TYPE_ID_INGREDIENT_VO = 2;
const int HIVE_TYPE_ID_PRODUCT_VO = 3;
const int HIVE_TYPE_ID_OPTION_VO = 4;
const int HIVE_TYPE_ID_RAW_MATERIAL_FOR_OPTION_VO = 5;
const int HIVE_TYPE_ID_REQUEST_TOPPING_VO = 6;

/// Box Names
const String BOX_NAME_SIZE_WITH_INGREDIENT_VO =
    "BOX_NAME_SIZE_WITH_INGREDIENT_VO";
const String BOX_NAME_INGREDIENT_VO = "BOX_NAME_SIZE_WITH_INGREDIENT_VO";
const String BOX_NAME_PRODUCT_VO = "BOX_NAME_PRODUCT_VO";
const String BOX_NAME_OPTION_VO = "BOX_NAME_OPTION_VO";
const String BOX_NAME_RAW_MATERIAL_FOR_OPTION_VO =
    "BOX_NAME_RAW_MATERIAL_FOR_OPTION_VO";
const String BOX_NAME_REQUEST_TOPPING_VO = "BOX_NAME_REQUEST_TOPPING_VO";
